name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" > ec2-key
        chmod 600 ec2-key

    - name: Deploy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ec2-key index.html ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/index.html
        ssh -o StrictHostKeyChecking=no -i ec2-key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'sudo mv /tmp/index.html /var/www/html/index.html'

